### ISSUE TITLE
FLOPS correct?

### ISSUE THREAD

**Issue by kodonnell** [Terminus-IMRC/qmkl#8]
Hi @Terminus-IMRC - just checking, but the FLOPS in the test are listed at e.g. 8.75459e+08 for RPI3 sgemm - isn't this only 0.8 GFLOPS i.e. < 5% of theoretical FLOPS? Whereas https://github.com/nineties/py-videocore lists the sgemm (parallel) as 8 GFLOPS? Or does this just mean your sgemm example is single threaded?

**Comment by Terminus-IMRC** [comment]
Yes, mine is single threaded and not efficient. His one is superior.
